# PROMETHEUS CONFIGURATION
#
# Note: This assumes prometheus and relevant exporters are installed and are available. To download 
# prometheus visit: https://prometheus.io/docs/prometheus/latest/installation/. 
#
# The below configuration specifies four distinct processes for scraping metrics with Prometheus
# 1. Prometheus server running on localhost:9090 
# 2. Substrate node process running on localhost:9615
# 3. Node exporter process running on localhost:9100
# 4. Process exporter process running localhost:9256
#
# Each process provides distinct metrics that are served up via Prometheus. 
# - Substrate node exporter provides chain specific metrics 
# - Node exporter designed to monitor the host system
# - Process exporter designed to report on selected processes
#
# There are many other config options for Prometheus, and you can read more about Prometheus configuration 
# at: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
#
# For an in-depth guide on how to setup Prometheus please follow: https://prometheus.io/docs/prometheus/latest/getting_started/

global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - localhost:9093
        
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'substrate_node'
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['localhost:9615']