[package]
name = "dkg-proposals-rpc-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.13.0", features = ["server"] }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }

codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23" }

pallet-dkg-proposals-runtime-api = { path = "./runtime-api", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "pallet-dkg-proposals-runtime-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-api/std"
]