relaychain:
  image: parity/polkadot:v0.9.17
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  # env:
  #   RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
- image: ghcr.io/webb-tools/dkg-node:3.0.0
  chain:
    base: local
    collators:
      - alice
      - bob
      - charlie
    sudo: alice
    runtimeGenesisConfig: # additonal genesis override
      session:
        keys:
          - [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, {"aura": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", "dkg": "KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL"}]
          - [5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty, {"aura": "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", "dkg": "KWByAN7WfZABWS5AoWqxriRmF5f2jnDqy3rB5pfHLGkY93ibN"}]
          - [5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, 5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y, {"aura": "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", "dkg": "KWBpGtyJLBkJERdZT1a1uu19c2uPpZm9nFd8SGtCfRUAT3Y4w"}]
  id: 2000
  parachain: true
  flags:
    - --rpc-methods=unsafe
    - -ldkg=debug
    - -ldkg_metadata=debug
    - -lruntime::offchain=debug
    - -ldkg_proposal_handler=debug
    - --force-authoring
    - --wasm-execution=compiled
    - --execution=wasm
  relaychainFlags:
    - --wasm-execution=compiled
    - --execution=wasm
  volumePath: /dkg/data
  nodes:
  - flags:
    - --alice
  - flags:
    - --bob
  - flags:
    - --charlie
