
//! Autogenerated weights for `pallet_dkg_proposals`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/dkg-standalone-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet-dkg-proposals
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --json
// --output
// ./pallets/dkg-proposals/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn set_maintainer() -> Weight;
	fn force_set_maintainer() -> Weight;
	fn set_threshold(_c: u32, ) -> Weight;
	fn set_resource(_c: u32, ) -> Weight;
	fn remove_resource() -> Weight;
	fn whitelist_chain() -> Weight;
	fn add_proposer() -> Weight;
	fn remove_proposer() -> Weight;
	fn acknowledge_proposal(_c: u32,) -> Weight;
	fn reject_proposal(_c: u32,) -> Weight;
	fn eval_vote_state(_c: u32,) -> Weight;
}

/// Weight functions for `pallet_dkg_proposals`.
pub struct WebbWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for WebbWeight<T> {
	// Storage: DKGProposals Maintainer (r:1 w:1)
	fn set_maintainer() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Maintainer (r:1 w:1)
	fn force_set_maintainer() -> Weight {
		(10_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals ProposerThreshold (r:0 w:1)
	fn set_threshold(_c: u32, ) -> Weight {
		(7_949_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Resources (r:0 w:1)
	fn set_resource(_c: u32, ) -> Weight {
		(1_266_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Resources (r:0 w:1)
	fn remove_resource() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals ChainNonces (r:1 w:1)
	fn whitelist_chain() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Proposers (r:1 w:1)
	// Storage: DKGProposals ProposerCount (r:1 w:1)
	fn add_proposer() -> Weight {
		(12_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: DKGProposals Proposers (r:1 w:1)
	// Storage: DKGProposals ProposerCount (r:1 w:1)
	fn remove_proposer() -> Weight {
		(13_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: DKGProposals Proposers (r:1 w:0)
	// Storage: DKGProposals ChainNonces (r:1 w:0)
	// Storage: DKGProposals Resources (r:1 w:0)
	// Storage: DKGProposals Votes (r:1 w:1)
	// Storage: DKGProposals ProposerThreshold (r:1 w:0)
	// Storage: DKGProposals ProposerCount (r:1 w:0)
	fn acknowledge_proposal(_c: u32, ) -> Weight {
		(27_981_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Proposers (r:1 w:0)
	// Storage: DKGProposals ChainNonces (r:1 w:0)
	// Storage: DKGProposals Resources (r:1 w:0)
	// Storage: DKGProposals Votes (r:1 w:1)
	// Storage: DKGProposals ProposerThreshold (r:1 w:0)
	// Storage: DKGProposals ProposerCount (r:1 w:0)
	fn reject_proposal(_c: u32, ) -> Weight {
		(28_205_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: DKGProposals Votes (r:1 w:1)
	// Storage: DKGProposals ProposerThreshold (r:1 w:0)
	// Storage: DKGProposals ProposerCount (r:1 w:0)
	fn eval_vote_state(_c: u32, ) -> Weight {
		(10_859_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}

}

impl WeightInfo for () {
	fn set_maintainer() -> Weight { 0 }
	fn force_set_maintainer() -> Weight { 0 }
	fn set_threshold(_c: u32, ) -> Weight { 0 }
	fn set_resource(_c: u32, ) -> Weight { 0 }
	fn remove_resource() -> Weight { 0 }
	fn whitelist_chain() -> Weight { 0 }
	fn add_proposer() -> Weight { 0 }
	fn remove_proposer() -> Weight { 0 }
	fn acknowledge_proposal(_c: u32,) -> Weight { 0 }
	fn reject_proposal(_c: u32,) -> Weight { 0 }
	fn eval_vote_state(_c: u32,) -> Weight { 0 }
}
