# the server bind addr
bind = "127.0.0.1:7777"
# the minimum number of clients required before starting the MockBlockchain (=n)
n_clients = 3
# threshold (=t)
threshold = 2
# the minimum latency in the network. Each client will receive updates at
# min_simulated_latency + random(0, 0.25*min_simulated_latency)
min_simulated_latency = "0ms"
# The number of positive cases to run
positive_cases = 10
unsigned_proposals_per_session = 2
