name: harness stress tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
  RUST_LOG: "dkg=trace"

jobs:
  # dkg-substrate integration tests
  harness:
    name: harness stress tests
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Restore Cache
        if: always()
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/registry
            target/release
            target/debug
          key: ${{ runner.os }}-cargo-index-${{ github.ref_name }}-harness-stress-tests

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Populate fixtures
        run: dvc pull

      - name: Install Protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Populate Fixtures
        run: dvc pull

      - name: t2n3 && 1 proposal per session
        run: cargo run --package dkg-test-orchestrator --features=debug-tracing -- --tmp /tmp --threshold 2 --n 3 --bind 127.0.0.1:7777 --n-tests 10 -p 1

      - name: t2n3 && 2 proposals per session
        run: cargo run --package dkg-test-orchestrator --features=debug-tracing -- --tmp /tmp --threshold 2 --n 3 --bind 127.0.0.1:7777 --n-tests 10 -p 2

      - name: t3n5 && 1 proposal per session
        run: cargo run --package dkg-test-orchestrator --features=debug-tracing -- --tmp /tmp --threshold 3 --n 5 --bind 127.0.0.1:7777 --n-tests 10 -p 1

      - name: t3n5 && 2 proposals per session
        run: cargo run --package dkg-test-orchestrator --features=debug-tracing -- --tmp /tmp --threshold 3 --n 5 --bind 127.0.0.1:7777 --n-tests 10 -p 2

      - name: Save Cache
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/registry
            target/release
            target/debug
          key: ${{ runner.os }}-cargo-index-${{ github.ref_name }}-harness-stress-tests
