name: Integration Tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
  RUST_LOG: "dkg=trace"

jobs:
  # dkg-substrate integration tests
  local_chain:
    name: Local Chain Tests
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Cache
        if: always()
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/registry
            target/release
            target/debug
          key: ${{ runner.os }}-cargo-index-${{ github.ref_name }}-local-chain-tests

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Protobuf and LLVM
        run: brew install protobuf llvm

      - name: Install cargo make
        run: cargo install cargo-make

      - name: Build Binary
        run: cargo make build-test

      - name: Run Tests
        run: cargo make integration-tests

      - name: Save Cache
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/registry
            target/release
            target/debug
          key: ${{ runner.os }}-cargo-index-${{ github.ref_name }}-local-chain-tests
